# Generated by Django 2.1.7 on 2020-01-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('precio', models.FloatField(blank=True, default=None, null=True)),
                ('vendidas', models.FloatField(blank=True, default=None, null=True)),
                ('envio', models.CharField(max_length=50)),
            ],
        ),
    ]
